### ISSUE TITLE
Nestia 도입.

### ISSUE THREAD

**Issue by koh1260** [CEUKIE/ckie-back#24]
## **✨ 작업 사항**

* Nestia를 도입한다.

## 🦄 To-do

- [ ] 라우터 nestia로 변경.
- [x] Swagger 등록 예시 작성.
- [ ] 필요에따라 Typia로 dto 변경.
